### ISSUE TITLE
Target staging api

### ISSUE THREAD

**Issue by NathanWalker** [ngatl/mobile-app#11]
Update this:
https://github.com/ngatl/mobile-app/blob/master/app/app.module.ts#L15
to: `https://ngatl.now.sh`

Then you don't need to run a local api.
Post comments here if that doesn't work.

**Comment by jlooper** [comment]
I'm consistently getting errors:

/Users/Looper/Documents/NativeScript/ng-atl-app/mobile-app
├── UNMET PEER DEPENDENCY rxjs@5.3.3
└── tns-ios@3.1.0 

Unable to apply changes on device: 061F5F6C-DE40-4A3D-972E-18B476E5C7C7. Error is: cp: no such file or directory: /Users/Looper/Documents/NativeScript/ng-atl-app/mobile-app/node_modules/rxjs/framework/*.

I'll upgrade the CLI, see if that helps

**Comment by jlooper** [comment]
upgrading the CLI and `npm run nuke` did the trick to move past this error.
